# 使用的 actions:
# https://github.com/marketplace/actions/automatic-releases
name: Main

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl rar python3 atomicparsley aria2 -y
          curl -LJO https://github.com/ytdl-org/youtube-dl/releases/latest/download/youtube-dl
          chmod +x ./youtube-dl
          ./youtube-dl --config-location dl.conf
          python3 ./deal_download_files.py


      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: ${{ github.run_id }}
          files: |
            result/*
        
